version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: proyecto_final_DO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - mi-red

  app:
    build: .
    command: sh -c "python manage.py && python run.py"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://postgres:admin@db:5432/proyecto_final_DO
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
