# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# Nombre del flujo de trabajo
name: CI with Docker

# Desencadenadores del flujo de trabajo: se ejecutará en push a la rama 'main' y en pull requests hacia 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job para construir y probar la aplicación
  build-and-test:
    # Entorno de ejecución: Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configurar Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    # Construir y ejecutar los contenedores
    - name: Build and start the containers
      run: docker-compose up -d --build

    # Creamos la BBDD
    - name: Run migrations 
      run: docker-compose exec -T app python manage.py

    # Ejecutar tests
    - name: Run tests
      run: docker-compose exec -T app python -m pytest

    # Paramos y limpiamos los contenedores
    - name: Shutdown and clean up
      if: always()
      run: docker-compose down