# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and start the containers
      run: docker-compose up -d --build
      
    - name: Wait for PostgreSQL
      run: |
       until PGPASSWORD=admin psql -h localhost -p 5432 -U postgres -c '\q'; do
          echo "Postgres is unavailable - sleeping"
          sleep 1
       done
       echo "Postgres is up - executing command"

    - name: Run migrations (if necessary)
      run: docker-compose exec -T app python manage.py

    - name: Run tests
      run: docker-compose exec -T app python -m pytest

    - name: Shutdown and clean up
      if: always()
      run: docker-compose down
